server:
  type: default
  applicationContextPath: /ripple-iaas
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: 53506
  adminConnectors:
    - type: http
      port: 53508
database:
    driverClass: com.mysql.jdbc.Driver
    user: dyfodbprd
    password: dyfodbprd123
    url: jdbc:mysql://dyfo-db-prod3.czynrz5a64r9.ap-south-1.rds.amazonaws.com:3306/iaas
    initialSize : 2
    minSize: 2
    maxSize: 2
logging:
  level: INFO
  loggers:
    "io.dropwizard": INFO
    "org.hibernate.SQL":
      level: DEBUG
      additive: false
      appenders:
        - type: console
  appenders:
    - type: console